### ISSUE TITLE
Questions about this repo

### ISSUE THREAD

**Issue by 0oshowero0** [haoyu0831/Covid-Mobility-Network-Analysis#2]
Hi, recently I saw a PNAS paper [A spatiotemporal decay model of human mobility when facing large-scale crises](https://www.pnas.org/doi/10.1073/pnas.2203042119), which links the open-source code to this repo. 

After a glance to this code, I didn't find many clues to link them. So I'm wondering are they the same thing? 

If so, another question is about the wij part in the model. Through the Method part and SI part I didn't find much description about how to calculate the wij. 

> W = (wij) LxL is a weight matrix with wij denoting the effect of region j on region i.

I'm wondering what it means and how to calculate it. Thanks!

**Comment by he-h** [comment]
Hi! Thank you for your interest in this repo. However, it contains the implementation of [Percolation of temporal hierarchical mobility networks during COVID-19](https://royalsocietypublishing.org/doi/full/10.1098/rsta.2021.0116). I believe the paper you mentioned linked the wrong code and I will contact the authors about this. Thank you!

**Comment by 0oshowero0** [comment]
Thank you for your reply! That's a great help.
